kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
    - echo start

- name: install
  image: composer
  commands:
    - composer install
  environment:
    action:
      from_secret: action
trigger:
  branch:
    - dev

